### PR TITLE
add castep2force

### PR DESCRIPTION
**Pull request by corwinkuiper**
A python script that can convert molecular dynamics files produced by castep to force configuration files used in potfit.

### CODE REVIEW

**Comment by dschopf** [comment]
Basically I am fine with the script and I did not find any major issues. The only problem I see is the frequent use of the f-strings. Since they are only supported starting with Python 3.6, there may be some users who could run into issues with them. But we can merge it and hope this never happens.

**Comment by p-bro** [comment]
Can we make that an explicit requirement, and get the code to throw a meaningful error if run by python before 3.6?

**Comment by corwinkuiper** [comment]
I'll change from using f-strings as I believe on lower python versions it will fail to parse the script.

**Comment by corwinkuiper** [comment]
I have removed the f-strings from the script, it now uses syntax used for the entirety of python3. I'm not too sure what the minimum python3 version is now, however.

**Comment by dschopf** [comment]
Looks good now. One final thing before merging is the header/license stuff. I have a branch with some python fixes which also adjusts the headers of most of the utils. Would you be willing to accept the default header like e.g. this one? https://github.com/potfit/potfit/blob/fix-python-utils/util/vasp2force

In case you want a different license please add it yourself.

**Comment by corwinkuiper** [comment]
I am happy to accept the default header.

**Pull request merged**
