### PR TITLE
fix issues found while testing

### PR DESCRIPTION
**Pull request by dschopf**

### CODE REVIEW

**Comment by arielzn** [comment]
daniel,

The fix for coulomb and dipole still have some issues. The memory assignment failing previously is solved.

But in order to have the proper number of non electrostatic parameters this line in 

https://github.com/dschopf/potfit/blob/eaed694385d603ea231659874e8edcc8cb02aeb9/src/potential_input_f0.c#L98

should be changed from 
 apt->total_ne_par = apt->total_par ;
to
 apt->total_ne_par = apt->total_par -  apt->globals;

otherwise "ne"  depends on globals amount, and the charge vector is badly defined for instance in force_elstat routine here
https://github.com/dschopf/potfit/blob/eaed694385d603ea231659874e8edcc8cb02aeb9/src/force_elstat.c#L186

I still have a really weird issue though.
Testing with a plain ELSTAT potential, I get wrong values for equivalent potential files one with globals another wihtout them.

I tracked that difference which happens only for total energies, not forces, to come from the loop for the short-range forces here
https://github.com/dschopf/potfit/blob/eaed694385d603ea231659874e8edcc8cb02aeb9/src/force_elstat.c#L336

at some iterations, when that contribution should be totally 0.0 (I'm using all constant 0.0 pair interactions), I see the fnval evaluated in that shor-range loop to be equal to the first charge in the elstat table.
Adding up on several loops total energies deviate at the end. The funny thing is that forces are always exactly the same. I don't get how the spline at
https://github.com/dschopf/potfit/blob/eaed694385d603ea231659874e8edcc8cb02aeb9/src/force_elstat.c#L338
is returning the value of that first charge sometimes.

I'll keep taking a look at this later.

**Comment by dschopf** [comment]
I just looked at the code for supporting global variables. It turned out this is really messy and
only works for "plain" potentials, e.g. not COULOMB, DIPOLE or chemical potentials.

i guess I will have to rewrite most parts of it for proper support. Could you provide the input files you
have been using to test these features? I am not sure I can reproduce your issues here.

**Comment by arielzn** [comment]
hi daniel,

sorry for the delay on providing this, I was very busy, i've just sent the input for checking this to the mailing list.

**Comment by dschopf** [comment]
I just merged this into master. Additional changes to be expected.

**Pull request merged**
