### PR TITLE
Merge mjwen/potfit to potfit/openkim

### PR DESCRIPTION
**Pull request by mjwen**
@dschopf Sorry for any inconvenience. I did not use Github before. 

I deleted my previous openkim branch. The commit history of the new one is much clear. The files in the new one should be the same as the previous one.

### CODE REVIEW

**Comment by dschopf** [comment]
Sorry for the delay, but I finally found some time to check this request once more.
I don't see any reason for not pulling. The only remaining question would be the following:
How stable do you consider the KIM feature? Can we already start merging it into trunk
or do you think it would be better if we have a separate branch for some time?

**Comment by mjwen** [comment]
I cannot guarantee that it is super stable, but I have been using it for doing some fitting work and no problems seem to occur. I think the way to improve it is giving it to the users and if bugs appear, we can fix it. So we can keep it in a separate branch, but we may also want to release a version of potfit that includes the KIM feature. Otherwise, if nobody has a chance to use, it seems difficult to find further bugs.

**Comment by p-bro** [comment]
Thanks @dschopf and @mjwen for getting this sorted.
I see that currently there is no automatic route to patch this into @potfit/master, is there?

**Comment by dschopf** [comment]
Probably not. If I have some time I will look into this and check out our options for merging
this into master.

**Pull request merged**
