### PR TITLE
Pair+Angular threebody potentials 

### PR DESCRIPTION
**Pull request by arielzn**
Hi,

I'm proposing this pull request which will provide two new Interaction models to potfit. One consisting on pair interactions+threebody potentials depending on atom's trios angles (force_ang.c), and these same interactions with electrostatics added (force_ang_elstat.c).

The precompiler option to trigger this interactions is the 'ang' keyword, e.g. potfit_apot_ang for the first case and potfit_apot_ang_coulomb for the second.

The way I implemented the angular part, is similar as how it was done for the MEAM potential. The Pair+Angles component is precisely

https://www.codecogs.com/eqnedit.php?latex=V&space;=&space;\frac{1}{2}&space;\sum&space;\phi_{ij}(r_{ij})&space;&plus;&space;\frac{1}{2}&space;\sum&space;f_{ij}(r_{ij})f_{ik}(r_{ik})g_i(\cos(\theta_{ijk}))

Coulomb interactions (I didn't port dipole) are computed the same as in all the others 'elstat' models.

With this approach we can consider immediately potentials such as the one used [here](http://www.sciencedirect.com/science/article/pii/S0022309396006047). It will be required only to introduce the special exponentials in eq. (2) in functions.c.

Or we can use it to consider non-bonded angular interactions as DL_POLY does for the three-body terms (see 'tbp' interaction, p. 174 in the [manual](http://goo.gl/3ns4i0) ). This can be achieved defining the f_ij = 1 between the pairs that will form 'triple-bonds' and with their cutoff controlling the central radius to account for angular bonded neighbours. Then, just choosing the _g_ function as an harmonic one.

In addition only for these interactions, I modified the way the threebody neighbours list are created in configs.c, by just adding the neighbours that fall inside the f_ij cutoff radius. This way a lot of memory (and time in _for_ loops) is saved for the systems with several species but angular interactions between only two types of them. And even in the case of having only two species, the angular interactions are usually considered among closest neighbours than the pair interactions, so we benefit of having a smaller angular-neighbours-list in this case also.

I added a couple of new functions also, an harmonic (despite parabola can contain this, I think is useful to have the classic formula), a Born-Mayer function, and an _acos(r)_ harmonic. The latter, by applying  _acos_ to the argument, is useful for defining an angular _g_ function acting on the angle itself.

I tested carefully energies and forces against LAMMPS pair/born/dsf style and I'm currently using it for developing a potential model, everything seems to be running fine.

I hope you consider all this implementations useful.

### CODE REVIEW

**Comment by dschopf** [comment]
Thanks for this patch. Maybe I can find some time next weekend for a proper review.

**Comment by dschopf** [comment]
Ok, I don't see any issues. However, I really dislike the pairang / ang mismatch in your code.
Would it be possible to use ang also for the Makefile and get rid of the the pair/pairang issue?

**Comment by arielzn** [comment]
Hi, 
Do you mean?
* rename new routines as  force_ang.c  and force_ang_elstat.c
* change keyword in the Makefile to use them with potfit_ang and potfit_ang_coulomb ?

I see no problem to modify  things in this direction. 
Shall I do it and submit the new commit ?

**Comment by dschopf** [comment]
Probably both. It would be nice to have matching preprocessor defines and internal names.
As long as we can avoid having name collisions without using crazy names I think we should do it.

**Comment by arielzn** [comment]
@dschopf finally I found some time to finish this pending task.

Everything renamed to refer as ANG to new potentials everywhere.

**Comment by dschopf** [comment]
That sounds great. Currently I only have little time and won't be able to check it until early September.

**Comment by dschopf** [comment]
I checked the code in the common files but not the implementations in details.
Compiling was working for all possible combinations, just need to update the homepage in the next couple of days.

**Comment by dschopf** [comment]
Using the old check_potfit.py code revealed a minor issue, which is fixed in bc4207f.

**Pull request merged**
