### PR TITLE
Merge rework branch to openkim branch:

### PR DESCRIPTION
**Pull request by p-bro**
This should take the openkim branch/fork past the rework gap. @dschopf - could you please give this a look, particularly with respect to the following questions:

- Did I get the modifications for the re-work correct?
- Are the files in the proper places?

I'll alert the openkim team as well, they should be able to feed back if I did break something.

### CODE REVIEW

**Comment by p-bro** [comment]
Next steps after this:

1.  bring potfit/openkim up-to-date with potfit/master
2. merge to master.

**Comment by dschopf** [comment]
Basically I don't see any issues. Running my compile script which builds (almost) all possible
potfit binaries I get lots of build errors for all kinds of options. This needs to be fixed.

There are some other things I would also like to point out:

- For the rework I wanted to get rid of the global variables. While it was impossible to remove them
without even more changes, I tried to groupd and mark them with the g_ prefix. In the
kim.h header there are some globals which don't follow that rule. Could you please use
a g_kim structure and move them inside? Or are there any reasons not to?
init_KIM() could then also be moved into initialize_global_variables().
- I don't understand how KIM works with MPI or is this currently not supported?
- So we finally got rid of the gaussion potential format 5?
- Some commits from master are still missing, like faec261.

**Comment by p-bro** [comment]
>  - So we finally got rid of the gaussion potential format 5?
I'd say so. If I need to resurrect it, it'll be under another name.
> - Some commits from master are still missing, like faec261.
I only merge it up to the rework. I wanted to do as few changes into this as possible, and then merge the remaining changes later.

For the remaining questions: that'll be @mjwen to answer.

**Comment by mjwen** [comment]
> Basically I don't see any issues. Running my compile script which builds (almost) all possible
potfit binaries I get lots of build errors for all kinds of options. This needs to be fixed.

Some options are not supported by openkim. I will give you a list of what they are.

> Could you please use a g_kim structure and move them inside? Or are there any reasons not to? init_KIM() could then also be moved into initialize_global_variables().

Sure. There is no problem to rename the variables with g_ prefix.

>- I don't understand how KIM works with MPI or is this currently not supported?

MPI is not supported currently.

**Comment by p-bro** [comment]
@mjwen I think the best thing to do was if you could create a pull request to merge.

**Comment by mjwen** [comment]
@p-bro So you mean I adapt the openkim branch to be compatible with the structure of mater? Sure, I'll let you know once finished.

**Comment by p-bro** [comment]
@mjwen I've done most of the work - just the points mentioned by Daniel need fixing. If you fork off https://github.com/p-bro/potfit/commit/df9871901f1a2b88c2d7a36eb94166c957654826 (which is my private fork off potfit, where the changes in this pull request are already included), make the changes, and submit a new pull request, then we can discuss this.

**Pull request merged**
