### PR TITLE
merge openkim to master

### PR DESCRIPTION
**Pull request by mjwen**
I've made changes to the oepnkim branch, such as grouping KIM global variables in a struct like "g_kim.x". Would you please take a look at it and then maybe we can merge it to master.
 
[kim-potfit_user_guide.pdf](https://github.com/potfit/potfit/files/389240/kim-potfit_user_guide.pdf) is a brief user guide to the openkim branch.

### CODE REVIEW

**Comment by dschopf** [comment]
I just checked out your changes and all the compile errors seem to be fixed.
It will take me a few days to check all the code changes in detail.

However, there is still the issue of the proper merge history of the trunk.
Maybe @p-bro has some news?

**Comment by p-bro** [comment]
I think the current potfit/master branch is merged with the proper_merge branch and should contain full history. I think I'll merge the changes suggested in this change request into the potfit/openkim branch, then merge the remaining updates to the master branch and finally suggest a merge to the current potfit/master branch. Does this sound reasonable?

**Comment by p-bro** [comment]
Also, I think this pull request should go to the potfit/openkim branch, not the master branch...

**Comment by p-bro** [comment]
@mjwen Apparently you can change the destination of the pull request. The base branch should be potfit/openkim not potfit/master.

**Comment by mjwen** [comment]
@p-bro @dschopf Thanks, I'll

**Pull request closed without merging**
