### PR TITLE
Merge mjwen/potfit to potfit/openkim

### PR DESCRIPTION
**Pull request by mjwen**
I closed the previous incorrect pull request to merge into potfit/master. And create this new one as @p-bro suggested.

### CODE REVIEW

**Comment by dschopf** [comment]
@mjwen I looked at your changes, but I still do have some questions:
- in the openkim branch we seem to be missing some commits from trunk (which is not your problem)
- what about the lib/geodesicLMv1.1? Do you want to add this to potfit as well?
- there are lots of files in examples/, is this by intent? Until now we didn't have an examples/ dir.
- you deleted some files in util/ (e.g. logo/ or potfit_setup). Is there a reason for this?

I will try to compile potfit with openkim support. Your last pull request had a PDF attached, could
you please provide the link again?

**Comment by dschopf** [comment]
Ok, I found the PDF and was able to setup my system for building potfit with openkim support.
Unfortunately there are build errors for certain options, like potfit_kim_stress:
```
force_kim.c: In function 'calc_forces':
force_kim.c:145:14: error: 'conf_us' undeclared (first use in this function)
         us = conf_us[h - g_mpi.firstconf];
```
I will upload my build script which will build all possible combinations of potfit.

**Comment by dschopf** [comment]
6621c4ee6d8fd1939dc9f5e74981e97497c65790 adds the script to the trunk
run it with `check_potfit.py --kim` for basic testing

**Comment by mjwen** [comment]
@dschopf 

>- what about the lib/geodesicLMv1.1? Do you want to add this to potfit as well?

Yes. This is a new local minimization algorithm. I can be used as an alternative of Powell's method. 
>- there are lots of files in examples/, is this by intent? Until now we didn't have an examples/ dir.

I think examples would be a place for people to start use the code. But it is totally fine for me to exclude the examples. 

>- you deleted some files in util/ (e.g. logo/ or potfit_setup). Is there a reason for this?

Possibly, it is done by accident.  Would you please add them back?

**Comment by mjwen** [comment]
I've fixed the code to support "stress" compiling option, and pushed it. @dschopf please let me know if other compiling options fail, and I'll fix them.

**Comment by dschopf** [comment]
Ok, I have not found any other compile error.

But I noticed that your branch rewrites history of many files. It deletes them and then re-adds them.
I don't think we can simply merge these changes. 

I would suggest the following approach:
Create a single patch file for all your changes against trunk. This patch should then only contain
actual changes and not rewrite the history anymore. You may then create (another) pull request
or just send me the patch so I can apply it.

**Pull request closed without merging**
